// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2JIYRNtN_BC6Pet6rTBZhkDHnFRjGYw',
    appId: '1:280029462774:web:33b5344196e2f444b36cd7',
    messagingSenderId: '280029462774',
    projectId: 'whatsapp-clone-2594e',
    authDomain: 'whatsapp-clone-2594e.firebaseapp.com',
    storageBucket: 'whatsapp-clone-2594e.firebasestorage.app',
    measurementId: 'G-FC6X004VQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGINNiKM62-P44tKoUUZ-KbYzlbZRCop4',
    appId: '1:280029462774:android:7bdd22e35736345ab36cd7',
    messagingSenderId: '280029462774',
    projectId: 'whatsapp-clone-2594e',
    storageBucket: 'whatsapp-clone-2594e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB2JIYRNtN_BC6Pet6rTBZhkDHnFRjGYw',
    appId: '1:280029462774:web:5af6518de1fdc6a2b36cd7',
    messagingSenderId: '280029462774',
    projectId: 'whatsapp-clone-2594e',
    authDomain: 'whatsapp-clone-2594e.firebaseapp.com',
    storageBucket: 'whatsapp-clone-2594e.firebasestorage.app',
    measurementId: 'G-BHMFFN0R9H',
  );
}
